### ISSUE TITLE
getattr operator fails with default value in _

### ISSUE THREAD

**Issue by kachayev** [kachayev/fn.py#23]
Easy to reproduce using `fn.op.foldr` (cause it's initially flip given function in order to work with c-level reducing).

``` python
>>> from fn import _ as XXX
>>> from fn.op import flip, foldr
>>>
>>> flip(XXX + XXX)
getattr((_ + _), __flipback__)
>>>
>>> foldr(XXX + XXX)([1,2,3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fn/op.py", line 70, in fold
    return iters.reduce(*args)
  File "fn/underscore.py", line 85, in __call__
    return self._callback(*args)
  File "fn/func.py", line 51, in __call__
    return self.f(*args, **kwargs)
  File "fn/func.py", line 32, in <lambda>
    return cls(lambda *args, **kwargs: f(g(*args, **kwargs)))
AttributeError: 'int' object has no attribute '__flipback__'
```

**Comment by kachayev** [comment]
Fixed in https://github.com/kachayev/fn.py/commit/03c7f6679c7c280d07ed11b87d72a8c15b8e302e
Appropriate test case is added.
