### ISSUE TITLE
Test fails for Python 3.x ('reduce' not defined)

### ISSUE THREAD

**Issue by microamp** [kachayev/fn.py#45]
Currently, the test fails for Python 3.x due to `reduce` not being defined.

```
======================================================================
ERROR: test_iterator (__main__.FingerTreeDequeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 1086, in test_iterator
    self.assertEqual(sum(range(1,20)), sum(Deque.from_iterable(range(1,20))))
  File "/home/microamp/devel/projs/fn.py/fn/immutable/finger.py", line 138, in from_iterable
    return FingerTree.from_iterable(lambda x: x, it)
  File "/home/microamp/devel/projs/fn.py/fn/immutable/finger.py", line 122, in from_iterable
    return reduce(lambda acc, curr: acc.push_front(curr), it, tree)
NameError: global name 'reduce' is not defined

----------------------------------------------------------------------
Ran 123 tests in 0.110s

FAILED (errors=1)
```

**Comment by microamp** [comment]
Added

```
from fn.uniform import reduce
```

to fix the issue. Will include it in the next pull request.
